fragment MetricsParts on Metrics {
  __typename
  category
  week
  data {
    __typename
    value
    unit
    trend
  }
}

fragment FindingsParts on Findings {
  __typename
  title
  category
  week
  date
  body
}

fragment AppsParts on Apps {
  __typename
  title
  status
  description
  body
}
