fragment Metrics_v2Parts on Metrics_v2 {
  __typename
  category
  week
  value
  unit
  trend
}

fragment FindingsParts on Findings {
  __typename
  title
  category
  week
  date
  body
}

fragment AppsParts on Apps {
  __typename
  title
  status
  description
  body
}
