//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  metrics_v2: Metrics_V2;
  metrics_v2Connection: Metrics_V2Connection;
  findings: Findings;
  findingsConnection: FindingsConnection;
  apps: Apps;
  appsConnection: AppsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMetrics_V2Args = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMetrics_V2ConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Metrics_V2Filter>;
};


export type QueryFindingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFindingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FindingsFilter>;
};


export type QueryAppsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAppsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AppsFilter>;
};

export type DocumentFilter = {
  metrics_v2?: InputMaybe<Metrics_V2Filter>;
  findings?: InputMaybe<FindingsFilter>;
  apps?: InputMaybe<AppsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Metrics_V2 | Findings | Apps | Folder;

export type Metrics_V2 = Node & Document & {
  __typename?: 'Metrics_v2';
  category: Scalars['String']['output'];
  week: Scalars['String']['output'];
  value?: Maybe<Scalars['Float']['output']>;
  unit?: Maybe<Scalars['String']['output']>;
  trend?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type Metrics_V2Filter = {
  category?: InputMaybe<StringFilter>;
  week?: InputMaybe<StringFilter>;
  value?: InputMaybe<NumberFilter>;
  unit?: InputMaybe<StringFilter>;
  trend?: InputMaybe<StringFilter>;
};

export type Metrics_V2ConnectionEdges = {
  __typename?: 'Metrics_v2ConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Metrics_V2>;
};

export type Metrics_V2Connection = Connection & {
  __typename?: 'Metrics_v2Connection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Metrics_V2ConnectionEdges>>>;
};

export type Findings = Node & Document & {
  __typename?: 'Findings';
  title: Scalars['String']['output'];
  category: Scalars['String']['output'];
  week: Scalars['String']['output'];
  date: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FindingsFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  week?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FindingsConnectionEdges = {
  __typename?: 'FindingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Findings>;
};

export type FindingsConnection = Connection & {
  __typename?: 'FindingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FindingsConnectionEdges>>>;
};

export type Apps = Node & Document & {
  __typename?: 'Apps';
  title: Scalars['String']['output'];
  status?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AppsFilter = {
  title?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AppsConnectionEdges = {
  __typename?: 'AppsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Apps>;
};

export type AppsConnection = Connection & {
  __typename?: 'AppsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AppsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateMetrics_v2: Metrics_V2;
  createMetrics_v2: Metrics_V2;
  updateFindings: Findings;
  createFindings: Findings;
  updateApps: Apps;
  createApps: Apps;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateMetrics_V2Args = {
  relativePath: Scalars['String']['input'];
  params: Metrics_V2Mutation;
};


export type MutationCreateMetrics_V2Args = {
  relativePath: Scalars['String']['input'];
  params: Metrics_V2Mutation;
};


export type MutationUpdateFindingsArgs = {
  relativePath: Scalars['String']['input'];
  params: FindingsMutation;
};


export type MutationCreateFindingsArgs = {
  relativePath: Scalars['String']['input'];
  params: FindingsMutation;
};


export type MutationUpdateAppsArgs = {
  relativePath: Scalars['String']['input'];
  params: AppsMutation;
};


export type MutationCreateAppsArgs = {
  relativePath: Scalars['String']['input'];
  params: AppsMutation;
};

export type DocumentUpdateMutation = {
  metrics_v2?: InputMaybe<Metrics_V2Mutation>;
  findings?: InputMaybe<FindingsMutation>;
  apps?: InputMaybe<AppsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  metrics_v2?: InputMaybe<Metrics_V2Mutation>;
  findings?: InputMaybe<FindingsMutation>;
  apps?: InputMaybe<AppsMutation>;
};

export type Metrics_V2Mutation = {
  category?: InputMaybe<Scalars['String']['input']>;
  week?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['Float']['input']>;
  unit?: InputMaybe<Scalars['String']['input']>;
  trend?: InputMaybe<Scalars['String']['input']>;
};

export type FindingsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  week?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AppsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Metrics_V2PartsFragment = { __typename: 'Metrics_v2', category: string, week: string, value?: number | null, unit?: string | null, trend?: string | null };

export type FindingsPartsFragment = { __typename: 'Findings', title: string, category: string, week: string, date: string, body?: any | null };

export type AppsPartsFragment = { __typename: 'Apps', title: string, status?: string | null, description?: any | null, body?: any | null };

export type Metrics_V2QueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Metrics_V2Query = { __typename?: 'Query', metrics_v2: { __typename: 'Metrics_v2', id: string, category: string, week: string, value?: number | null, unit?: string | null, trend?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Metrics_V2ConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Metrics_V2Filter>;
}>;


export type Metrics_V2ConnectionQuery = { __typename?: 'Query', metrics_v2Connection: { __typename?: 'Metrics_v2Connection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Metrics_v2ConnectionEdges', cursor: string, node?: { __typename: 'Metrics_v2', id: string, category: string, week: string, value?: number | null, unit?: string | null, trend?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FindingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FindingsQuery = { __typename?: 'Query', findings: { __typename: 'Findings', id: string, title: string, category: string, week: string, date: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FindingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FindingsFilter>;
}>;


export type FindingsConnectionQuery = { __typename?: 'Query', findingsConnection: { __typename?: 'FindingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FindingsConnectionEdges', cursor: string, node?: { __typename: 'Findings', id: string, title: string, category: string, week: string, date: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AppsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AppsQuery = { __typename?: 'Query', apps: { __typename: 'Apps', id: string, title: string, status?: string | null, description?: any | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AppsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AppsFilter>;
}>;


export type AppsConnectionQuery = { __typename?: 'Query', appsConnection: { __typename?: 'AppsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AppsConnectionEdges', cursor: string, node?: { __typename: 'Apps', id: string, title: string, status?: string | null, description?: any | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Metrics_V2PartsFragmentDoc = gql`
    fragment Metrics_v2Parts on Metrics_v2 {
  __typename
  category
  week
  value
  unit
  trend
}
    `;
export const FindingsPartsFragmentDoc = gql`
    fragment FindingsParts on Findings {
  __typename
  title
  category
  week
  date
  body
}
    `;
export const AppsPartsFragmentDoc = gql`
    fragment AppsParts on Apps {
  __typename
  title
  status
  description
  body
}
    `;
export const Metrics_V2Document = gql`
    query metrics_v2($relativePath: String!) {
  metrics_v2(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Metrics_v2Parts
  }
}
    ${Metrics_V2PartsFragmentDoc}`;
export const Metrics_V2ConnectionDocument = gql`
    query metrics_v2Connection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Metrics_v2Filter) {
  metrics_v2Connection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Metrics_v2Parts
      }
    }
  }
}
    ${Metrics_V2PartsFragmentDoc}`;
export const FindingsDocument = gql`
    query findings($relativePath: String!) {
  findings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FindingsParts
  }
}
    ${FindingsPartsFragmentDoc}`;
export const FindingsConnectionDocument = gql`
    query findingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FindingsFilter) {
  findingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FindingsParts
      }
    }
  }
}
    ${FindingsPartsFragmentDoc}`;
export const AppsDocument = gql`
    query apps($relativePath: String!) {
  apps(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AppsParts
  }
}
    ${AppsPartsFragmentDoc}`;
export const AppsConnectionDocument = gql`
    query appsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AppsFilter) {
  appsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AppsParts
      }
    }
  }
}
    ${AppsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      metrics_v2(variables: Metrics_V2QueryVariables, options?: C): Promise<{data: Metrics_V2Query, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Metrics_V2QueryVariables, query: string}> {
        return requester<{data: Metrics_V2Query, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Metrics_V2QueryVariables, query: string}, Metrics_V2QueryVariables>(Metrics_V2Document, variables, options);
      },
    metrics_v2Connection(variables?: Metrics_V2ConnectionQueryVariables, options?: C): Promise<{data: Metrics_V2ConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Metrics_V2ConnectionQueryVariables, query: string}> {
        return requester<{data: Metrics_V2ConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Metrics_V2ConnectionQueryVariables, query: string}, Metrics_V2ConnectionQueryVariables>(Metrics_V2ConnectionDocument, variables, options);
      },
    findings(variables: FindingsQueryVariables, options?: C): Promise<{data: FindingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FindingsQueryVariables, query: string}> {
        return requester<{data: FindingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FindingsQueryVariables, query: string}, FindingsQueryVariables>(FindingsDocument, variables, options);
      },
    findingsConnection(variables?: FindingsConnectionQueryVariables, options?: C): Promise<{data: FindingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FindingsConnectionQueryVariables, query: string}> {
        return requester<{data: FindingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FindingsConnectionQueryVariables, query: string}, FindingsConnectionQueryVariables>(FindingsConnectionDocument, variables, options);
      },
    apps(variables: AppsQueryVariables, options?: C): Promise<{data: AppsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AppsQueryVariables, query: string}> {
        return requester<{data: AppsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AppsQueryVariables, query: string}, AppsQueryVariables>(AppsDocument, variables, options);
      },
    appsConnection(variables?: AppsConnectionQueryVariables, options?: C): Promise<{data: AppsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AppsConnectionQueryVariables, query: string}> {
        return requester<{data: AppsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AppsConnectionQueryVariables, query: string}, AppsConnectionQueryVariables>(AppsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.6/content/190b6b72-2fd9-47d2-801b-43c84175955b/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  